### ISSUE TITLE
Create Documentation( README )

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/sysbot#49]
## Description
As a developer and/or user,
I need properly formatted documentation,
so that I can effectively use Sysbot.

### Update [Required]
- [ ] Create documentation.
- [ ] Documentation should be a readme explaining all functionalities and how to set up the project.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
12 hours

**Comment by sara-02** [comment]
## Task List
- [ ] Swagger API Doc
- [ ] Updated README with Project Description(what, why, how of the project)
- [ ] Update README with Project Installation Steps + Python version specified
- [ ] Link to Systers Sysbot channel for further details

## Stretch goal
- [ ] Steps on how can user obtain their own token and use them

**Comment by sara-02** [comment]
@sammy1997 Do you want me to create a separate issue for the API Doc?

**Comment by sammy1997** [comment]
Yes sure

**Comment by sammy1997** [comment]
@ramitsawhney27 As @sara-02 has created a separate issue for API documentation, I am updating this one for the readme.
